"""
Integration tests for the /consent (GET) and /consent/approve (POST) endpoints.

Tests cover:
  1. Rate limiting (DOS prevention) – endpoint-specific standard rate limit
  2. Payload / field-size limits (FastAPI 422 responses)
  3. Flood probe across multiple rate-limit windows

Flow dependency:
  /register  →  /authorize  →  /consent  →  /consent/approve

CSRF note for /consent/approve:
  The endpoint uses a session-based CSRF token generated by GET /consent.
  Correct testing of /consent/approve requires:
    1. A requests.Session() so the session cookie is carried across requests.
    2. GET /consent  – sets the session cookie and returns the CSRF token
       embedded in the HTML form.
    3. POST /consent/approve – submits the session cookie + CSRF token.

  For rate-limit and payload-size tests, a session is still used but CSRF
  validity is not a concern – the rate limiter runs before CSRF validation,
  so 403 (bad CSRF) is the "normal" failure, and 429 indicates the rate
  limiter fired first.

NOTE on 422 vs 429 ordering:
  See authorize_endpoint.py for the same caveat on dependency-resolution order.
"""

import os
import re
import time
from urllib.parse import parse_qs, urlparse
import base64
import hashlib
import secrets

import requests
from dotenv import load_dotenv

load_dotenv()

BASE_URL           = os.getenv("MCP_SERVER_PUBLIC_URL")
REGISTER_URL       = f"{BASE_URL}/register"
AUTHORIZE_URL      = f"{BASE_URL}/authorize"
CONSENT_URL        = f"{BASE_URL}/consent"
CONSENT_APPROVE_URL = f"{BASE_URL}/consent/approve"

# ── Configurable rate-limit parameters ───────────────────────────────────────
STANDARD_RATE_LIMIT_COUNT  = int(os.getenv("PRIVATE_OAUTH_STANDARD_RATE_LIMIT_COUNT",  "5"))
STANDARD_RATE_LIMIT_WINDOW = int(os.getenv("PRIVATE_OAUTH_STANDARD_RATE_LIMIT_WINDOW", "60"))

# ── Configurable field constraints (mirror remote_auth.py Query/Form annotations) ─
MAX_TRANSACTION_ID_LENGTH = 100   # Query(..., max_length=100) on /consent
                                   # Form(...,  max_length=100) on /consent/approve

# ── Fixed test values ─────────────────────────────────────────────────────────
VALID_REDIRECT_URI = "https://example.com/callback"
REGISTER_PAYLOAD = {
    "client_name": "ConsentTestClient",
    "redirect_uris": [VALID_REDIRECT_URI],
    "grant_types": ["authorization_code"],
    "response_types": ["code"],
}

_CSRF_RE = re.compile(
    r'<input[^>]+name=["\']csrf_token["\'][^>]+value=["\']([^"\']+)["\']'
    r'|<input[^>]+value=["\']([^"\']+)["\'][^>]+name=["\']csrf_token["\']',
    re.IGNORECASE,
)


# ── Shared helpers ────────────────────────────────────────────────────────────

def register_client() -> dict:
    """Register a fresh DCR client and return the full response JSON."""
    r = requests.post(REGISTER_URL, json=REGISTER_PAYLOAD)
    assert r.status_code == 200, f"Registration failed: {r.status_code} {r.text}"
    return r.json()


def make_pkce_pair(verifier_length: int = 64) -> tuple[str, str]:
    """Return (code_verifier, code_challenge) for S256 PKCE."""
    code_verifier  = secrets.token_urlsafe(verifier_length)[:verifier_length]
    digest         = hashlib.sha256(code_verifier.encode("ascii")).digest()
    code_challenge = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")
    return code_verifier, code_challenge


def get_transaction_id(client_id: str) -> str | None:
    """
    Call /authorize with valid params and parse the transaction_id from the
    302 Location header (redirect to /consent?transaction_id=<uuid>).
    Returns None on unexpected status.
    """
    _, code_challenge = make_pkce_pair()
    params = {
        "client_id":            client_id,
        "redirect_uri":         VALID_REDIRECT_URI,
        "scope":                "ZohoAnalytics.fullaccess.all",
        "state":                "statevalue1",
        "code_challenge":       code_challenge,
        "code_challenge_method": "S256",
    }
    r = requests.get(AUTHORIZE_URL, params=params, allow_redirects=False)
    if r.status_code != 302:
        return None
    location = r.headers.get("Location", "")
    qs       = parse_qs(urlparse(location).query)
    return qs.get("transaction_id", [None])[0]


def get_csrf_token(session: requests.Session, transaction_id: str) -> str | None:
    """
    Use the provided session to GET /consent and extract the CSRF token from
    the hidden form field in the returned HTML.
    The session cookie is updated in-place so the CSRF token remains valid for
    subsequent POST requests within the same session.
    """
    r = session.get(CONSENT_URL, params={"transaction_id": transaction_id})
    if r.status_code != 200:
        return None
    match = _CSRF_RE.search(r.text)
    if not match:
        return None
    return match.group(1) or match.group(2)


# ── /consent (GET) rate-limit tests ──────────────────────────────────────────

def test_consent_rate_limit() -> bool:
    """
    Exhaust the standard rate-limit bucket on GET /consent and verify 429.

    A fresh transaction_id is obtained once; subsequent requests with the same
    (already-invalid-after-expiry but syntactically valid) id still count
    toward the rate limiter because the limiter runs before the transaction
    lookup.
    """
    print("\n=== GET /consent Rate Limit Test ===")
    client         = register_client()
    transaction_id = get_transaction_id(client["client_id"])
    assert transaction_id, "Could not obtain a transaction_id via /authorize"

    for i in range(STANDARD_RATE_LIMIT_COUNT + 3):
        r = requests.get(CONSENT_URL, params={"transaction_id": transaction_id})
        print(f"  Request {i+1}: status={r.status_code}")
        if r.status_code == 429:
            print("  ✓ Rate limit triggered as expected")
            return True

    print("  ✗ Rate limit was NOT triggered after all requests")
    return False


def test_consent_tokens_refill_after_window():
    """Exhaust the /consent bucket, wait for it to refill, confirm success."""
    print(f"\n=== GET /consent Token Refill After {STANDARD_RATE_LIMIT_WINDOW}s Window ===")
    client         = register_client()
    transaction_id = get_transaction_id(client["client_id"])
    assert transaction_id, "Could not obtain a transaction_id via /authorize"

    for i in range(STANDARD_RATE_LIMIT_COUNT + 1):
        r = requests.get(CONSENT_URL, params={"transaction_id": transaction_id})
        print(f"  Exhaust {i+1}: {r.status_code}")

    wait = STANDARD_RATE_LIMIT_WINDOW + 5
    print(f"  Waiting {wait}s for bucket to refill...")
    time.sleep(wait)

    # New transaction for the post-refill check
    client2        = register_client()
    transaction_id2 = get_transaction_id(client2["client_id"])
    assert transaction_id2, "Could not obtain post-refill transaction_id"

    for i in range(2):
        r = requests.get(CONSENT_URL, params={"transaction_id": transaction_id2})
        print(f"  Post-refill {i+1}: {r.status_code}")
        assert r.status_code in (200, 400), (
            f"Expected 200 or 400 after refill, got {r.status_code}"
        )
    print("  ✓ Bucket refilled correctly after window")


def test_different_ip_independent_limits_consent():
    """
    Validate per-IP bucket isolation for /consent via X-Forwarded-For.
    See authorize_endpoint.py for proxy configuration requirements.
    """
    print("\n=== GET /consent Per-IP Independent Limits ===")
    print("  ⚠ Requires BEHIND_PROXY=True and the test host in TRUSTED_PROXY_LIST")

    client         = register_client()
    transaction_id = get_transaction_id(client["client_id"])
    assert transaction_id, "Could not obtain a transaction_id via /authorize"

    headers_ip1 = {"X-Forwarded-For": "10.0.0.3"}
    headers_ip2 = {"X-Forwarded-For": "10.0.0.4"}

    for i in range(STANDARD_RATE_LIMIT_COUNT + 1):
        r = requests.get(
            CONSENT_URL,
            params={"transaction_id": transaction_id},
            headers=headers_ip1,
        )
        print(f"  IP1 request {i+1}: {r.status_code}")

    r = requests.get(
        CONSENT_URL,
        params={"transaction_id": transaction_id},
        headers=headers_ip2,
    )
    print(f"  IP2 request after IP1 exhausted: {r.status_code}")
    if r.status_code in (200, 400):
        print("  ✓ Per-IP rate limiting working (IP2 unaffected by IP1)")
    else:
        print("  ⚠ IP2 was also blocked — rate limiter may be global, not per-IP")


# ── /consent (GET) payload-limit tests ───────────────────────────────────────

def test_consent_transaction_id_too_long():
    """transaction_id > MAX_TRANSACTION_ID_LENGTH chars → 422."""
    print("\n=== GET /consent transaction_id Too Long ===")
    r = requests.get(
        CONSENT_URL,
        params={"transaction_id": "x" * (MAX_TRANSACTION_ID_LENGTH + 1)},
    )
    print(f"  Status: {r.status_code}")
    assert r.status_code == 422, f"Expected 422, got {r.status_code}"
    print("  ✓ Rejected oversized transaction_id")


def test_consent_missing_transaction_id():
    """Omitting the required transaction_id → 422."""
    print("\n=== GET /consent Missing transaction_id ===")
    r = requests.get(CONSENT_URL)
    print(f"  Status: {r.status_code}")
    assert r.status_code == 422, f"Expected 422, got {r.status_code}"
    print("  ✓ Rejected request with missing transaction_id")


def test_consent_invalid_transaction_id():
    """A syntactically valid but non-existent transaction_id → 400."""
    print("\n=== GET /consent Invalid (Non-existent) transaction_id ===")
    r = requests.get(
        CONSENT_URL,
        params={"transaction_id": "nonexistent-transaction-id-00000000"},
    )
    print(f"  Status: {r.status_code}")
    assert r.status_code == 400, f"Expected 400, got {r.status_code}"
    print("  ✓ Returned 400 for unknown transaction_id")


# ── /consent/approve (POST) rate-limit tests ─────────────────────────────────

def test_consent_approve_rate_limit() -> bool:
    """
    Exhaust the standard rate-limit bucket on POST /consent/approve.

    The rate-limiter dependency runs before CSRF validation, so repeated
    requests with an invalid CSRF token will return 403 until the bucket is
    exhausted, after which they return 429.  We count the first 429 as the
    signal that the rate limiter fired correctly.
    """
    print("\n=== POST /consent/approve Rate Limit Test ===")
    # Any syntactically valid transaction_id is fine; rate-limit fires before
    # transaction or CSRF lookup.
    dummy_txn_id = "a" * 36    # UUID-length, within max_length=100

    for i in range(STANDARD_RATE_LIMIT_COUNT + 3):
        r = requests.post(
            CONSENT_APPROVE_URL,
            data={
                "transaction_id": dummy_txn_id,
                "csrf_token":     "invalid-csrf-token",
            },
        )
        print(f"  Request {i+1}: status={r.status_code}")
        if r.status_code == 429:
            print("  ✓ Rate limit triggered as expected")
            return True

    print("  ✗ Rate limit was NOT triggered after all requests")
    return False


def test_consent_approve_with_valid_csrf():
    """
    Obtain a real CSRF token via GET /consent and submit it to POST
    /consent/approve.  The expected outcome is 302 (redirect to upstream
    provider) if the transaction is still valid, or 400 if it has expired.

    This test validates that the endpoint behaves correctly with proper CSRF
    tokens – i.e. it does NOT return 403.
    """
    print("\n=== POST /consent/approve With Valid CSRF Token ===")
    session        = requests.Session()
    client         = register_client()
    transaction_id = get_transaction_id(client["client_id"])
    assert transaction_id, "Could not obtain a transaction_id via /authorize"

    csrf_token = get_csrf_token(session, transaction_id)
    assert csrf_token, "Could not extract CSRF token from /consent HTML"
    print(f"  CSRF token obtained: {csrf_token[:8]}...{csrf_token[-4:]}")

    r = session.post(
        CONSENT_APPROVE_URL,
        data={
            "transaction_id": transaction_id,
            "csrf_token":     csrf_token,
        },
        allow_redirects=False,
    )
    print(f"  Status: {r.status_code}")
    assert r.status_code in (302, 400), (
        f"Expected 302 (redirect to upstream) or 400 (expired txn), got {r.status_code}"
    )
    if r.status_code == 302:
        print(f"  ✓ Redirecting to upstream provider: {r.headers.get('Location', '')[:60]}...")
    else:
        print("  ✓ Transaction expired as expected (400)")


# ── /consent/approve (POST) payload-limit tests ───────────────────────────────

def test_consent_approve_transaction_id_too_long():
    """transaction_id > MAX_TRANSACTION_ID_LENGTH chars in form body → 422."""
    print("\n=== POST /consent/approve transaction_id Too Long ===")
    r = requests.post(
        CONSENT_APPROVE_URL,
        data={
            "transaction_id": "x" * (MAX_TRANSACTION_ID_LENGTH + 1),
            "csrf_token":     "somecsrftoken",
        },
    )
    print(f"  Status: {r.status_code}")
    assert r.status_code == 422, f"Expected 422, got {r.status_code}"
    print("  ✓ Rejected oversized transaction_id in form body")


def test_consent_approve_missing_fields():
    """POST /consent/approve with no form fields → 422 (required fields absent)."""
    print("\n=== POST /consent/approve Missing Required Fields ===")
    r = requests.post(CONSENT_APPROVE_URL, data={})
    print(f"  Status: {r.status_code}")
    assert r.status_code == 422, f"Expected 422, got {r.status_code}"
    print("  ✓ Rejected request with missing form fields")


# ── DOS flood probe ───────────────────────────────────────────────────────────

def test_consent_large_flood():
    """
    Attempt DOS via repeated GET /consent requests carrying a max-length
    transaction_id.

    Each accepted request triggers a transaction store lookup and (if valid)
    a CSRF token generation + HTML template render.  Sustained flood across
    windows may cause memory pressure from stored CSRF sessions or template
    overhead.
    """
    print("\n=== GET /consent Large Payload Flood (DOS probe) ===")

    client         = register_client()
    transaction_id = get_transaction_id(client["client_id"])
    assert transaction_id, "Could not obtain a transaction_id via /authorize"

    # Use a max-length (but valid format) transaction_id after the real one
    # is consumed, to measure payload-handling cost per request.
    # For the initial requests use the real transaction_id (triggers full path).
    max_txn_id = transaction_id   # real UUID-format id, well within 100 chars

    NUM_WINDOWS         = 3
    REQUESTS_PER_WINDOW = STANDARD_RATE_LIMIT_COUNT - 1
    WINDOW_WAIT_SECONDS = STANDARD_RATE_LIMIT_WINDOW + 5

    total_sent = total_ok = total_rate_limited = total_errors = 0
    response_times: list[float] = []

    for window in range(NUM_WINDOWS):
        print(f"\n  Window {window+1}/{NUM_WINDOWS}  "
              f"(cumulative successful so far: {total_ok})")

        for i in range(REQUESTS_PER_WINDOW):
            start = time.monotonic()
            try:
                r       = requests.get(
                    CONSENT_URL,
                    params={"transaction_id": max_txn_id},
                    timeout=10,
                )
                elapsed = time.monotonic() - start
                response_times.append(elapsed)
                total_sent += 1

                if r.status_code in (200, 400):
                    total_ok += 1
                    print(f"    [{window+1}-{i+1}] {r.status_code}  ({elapsed:.3f}s)")
                elif r.status_code == 429:
                    total_rate_limited += 1
                    print(f"    [{window+1}-{i+1}] 429 Rate Limited ({elapsed:.3f}s)")
                elif r.status_code >= 500:
                    total_errors += 1
                    print(f"    [{window+1}-{i+1}] {r.status_code} SERVER ERROR")
                else:
                    print(f"    [{window+1}-{i+1}] {r.status_code}  ({elapsed:.3f}s)")

            except requests.exceptions.ConnectionError:
                elapsed = time.monotonic() - start
                total_errors += 1
                total_sent   += 1
                print(f"    [{window+1}-{i+1}] CONNECTION ERROR ({elapsed:.3f}s)")
            except requests.exceptions.Timeout:
                total_errors += 1
                total_sent   += 1
                print(f"    [{window+1}-{i+1}] TIMEOUT")

        # Obtain a fresh transaction_id for the next window
        client2         = register_client()
        new_txn         = get_transaction_id(client2["client_id"])
        if new_txn:
            max_txn_id  = new_txn

        if window < NUM_WINDOWS - 1:
            print(f"  Waiting {WINDOW_WAIT_SECONDS}s for rate-limit bucket to refill...")
            time.sleep(WINDOW_WAIT_SECONDS)

    # ── Final health probe ────────────────────────────────────────────────────
    print("\n  Final health probe...")
    try:
        probe = requests.get(
            CONSENT_URL,
            params={"transaction_id": "probe-transaction-id-0000000000000000"},
            timeout=10,
        )
        print(f"  Probe: {probe.status_code}")
        server_alive = probe.status_code in (200, 400, 429)
    except (requests.exceptions.ConnectionError, requests.exceptions.Timeout):
        server_alive = False
        print("  Probe FAILED — server unreachable after flood")

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\n  === Summary ===")
    print(f"  Total requests : {total_sent}")
    print(f"  Non-error      : {total_ok}")
    print(f"  Rate Limited   : {total_rate_limited}")
    print(f"  Server Errors  : {total_errors}")

    if response_times:
        half       = max(len(response_times) // 2, 1)
        avg_first  = sum(response_times[:half]) / half
        avg_second = sum(response_times[half:]) / max(len(response_times) - half, 1)
        print(f"  Avg latency first half  : {avg_first:.3f}s")
        print(f"  Avg latency second half : {avg_second:.3f}s")
        if avg_second > avg_first * 1.5:
            print("  ⚠ Latency increased >50% — possible memory pressure")
        else:
            print("  ✓ Latency remained stable")

    if not server_alive:
        print("  ✗ Server unreachable after flood — possible OOM crash")
    elif total_errors > 0:
        print("  ⚠ Server returned errors — investigate memory risk")
    else:
        print("  ✓ Server survived; review server-side memory metrics for long-term risk")


if __name__ == "__main__":
    # Payload / field-size checks (fast, no waits)
    test_consent_transaction_id_too_long()
    test_consent_missing_transaction_id()
    test_consent_invalid_transaction_id()
    test_consent_approve_transaction_id_too_long()
    test_consent_approve_missing_fields()

    # CSRF-aware functional test
    test_consent_approve_with_valid_csrf()

    # Rate-limit checks
    test_consent_rate_limit()
    test_different_ip_independent_limits_consent()
    test_consent_approve_rate_limit()
    test_consent_large_flood()

    # Long-running refill test — comment out if time-constrained
    test_consent_tokens_refill_after_window()
